cookie:
  expiry_days: 30
  key: abcd
  name: sankalp.ai
credentials:
  usernames:
    demo:
      email: demo@email.com
      experience: 2
      job_role: Data Analyst
      name: Demo Test
      password: $2b$12$QYtyGZMV2i9duB19zPP0JehcdbOzGMjOKR/Wc/CTEPlgFl3qLZjNm
      skills: Python, SQL, Power BI
